check build status

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -60,7 +60,14 @@ runs:
       shell: bash
     - name: Create build directory
       id: viz-build
-      run: kedro viz build
+      run: kedro viz build || echo "::set-env name=BUILD_STATUS::failed"
+      shell: bash
+    - name: Check build status
+      run: |
+        if [ "${{ env.BUILD_STATUS }}" == "failed" ]; then
+          echo "Build failed. Deployment skipped."
+          exit 1
+        fi
       shell: bash
     - name: Deploy to GitHub Pages
       uses: peaceiris/actions-gh-pages@v3
